spring.application.name=banking-api

spring.datasource.url=${BANKING_DB_URL:jdbc:postgresql://localhost:5433/securebank}
spring.datasource.username=banking_app
spring.datasource.password=${BANKING_APP_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10

spring.flyway.url=${BANKING_DB_URL:jdbc:postgresql://localhost:5433/securebank}
spring.flyway.user=banking_migrator
spring.flyway.password=${BANKING_MIGRATOR_PASSWORD}
spring.flyway.default-schema=banking
spring.flyway.schemas=banking
spring.flyway.create-schemas=false
spring.flyway.clean-disabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=banking

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
